name: Deploy Lambda to AWS

on:
  push:
    branches:
      - master  # Trigger deployment when changes are pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Test if the credentials are being loaded correctly (optional)
    - name: Test Secrets (Optional Debugging Step)
      run: |
        echo "AWS Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS Secret Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    # Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Specify the region where your Lambda function is hosted

    # Create a zip file of your Lambda function code
    - name: Create zip file for Lambda
      run: |
        zip -r lambda_function.zip .  # Ensure this is the directory of your Lambda function

    # Update the Lambda function with the new zip file
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name math-toy --zip-file fileb://lambda_function.zip

